### ISSUE TITLE
User got 500 attempting to link a Google account, but it succeeded anyway

### ISSUE THREAD

**Issue by egnor** [deathandmayhem/jolly-roger#1945]
In testing, one user reported clicking the button to link a Google account, and went through the OAuth flow, but then the JR interface gave an error bar saying 500 server error. At that time this message was printed to the server's console:

```
Jan 08 05:19:15 egnor-2020 mise[69591]: Exception while invoking method 'Users.methods.linkGoogleAccount' TypeError: Cannot read property 'serviceData' of undefined
Jan 08 05:19:15 egnor-2020 mise[69591]:     at imports/server/methods/linkUserGoogleAccount.ts:28:38
Jan 08 05:19:15 egnor-2020 mise[69591]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 08 05:19:15 egnor-2020 mise[69591]:  => awaited here:
Jan 08 05:19:15 egnor-2020 mise[69591]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at imports/server/methods/defineMethod.ts:54:9
Jan 08 05:19:15 egnor-2020 mise[69591]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 08 05:19:15 egnor-2020 mise[69591]:  => awaited here:
Jan 08 05:19:15 egnor-2020 mise[69591]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at packages/meteor.js:367:22
Jan 08 05:19:15 egnor-2020 mise[69591]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at packages/meteor.js:365:18
Jan 08 05:19:15 egnor-2020 mise[69591]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at packages/ddp-server/livedata_server.js:827:46
Jan 08 05:19:15 egnor-2020 mise[69591]:     at new Promise (<anonymous>)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at Session.method (packages/ddp-server/livedata_server.js:775:23)
Jan 08 05:19:15 egnor-2020 mise[69591]:     at packages/ddp-server/livedata_server.js:639:43
```

Weirdly, however, the account DID get linked, the Google username and ID are stored in their user record and it shows as linked in the UI. So maybe somehow the method got invoked twice?? However, I only see one instance of "Linking user to Google account" in the logs, and that's for my own account, not this one.

**Comment by ebroder** [comment]
Tracing through the code a little bit, it looks like pending OAuth credentials are [pulled out of a database record and then deleted](https://github.com/meteor/meteor/blob/8cacebef97536407fb0053f55161b77db6b3190b/packages/oauth/pending_credentials.js#L75-L88), so if the `linkUserGoogleAccount` method got called twice, this sort of thing might happen. Meteor's client-side code [will re-call a method](https://docs.meteor.com/api/methods#:~:text=If%20a%20client,set%20to%20true.) if it doesn't get a response back due to a connection drop or similar.

I'm not entirely sure how to make this idempotent. I think we'd probably have to save the OAuth credentials (or at least the token) so we could tell if a request was being replayed.

**Comment by egnor** [comment]
Simply checking the username they're trying to link might do it? Or do we not know that at the point in question?

**Comment by ebroder** [comment]
AFAIK, it's not exposed to the client (or at least Meteor's abstractions over the OAuth handshake don't expose it) and on the server-side it's kept in that database record that's already been deleted
