### ISSUE TITLE
User got 500 attempting to create a puzzle

### ISSUE THREAD

**Issue by egnor** [deathandmayhem/jolly-roger#1947]
A user (https://github.com/grahac) who had recently been granted Operator permissions was attempting to create a puzzle, and the interface reported a 500 server error. In the server logs, this stack trace showed up:

```
Jan 08 06:44:18 egnor-2020 mise[69591]: Exception while invoking method 'Puzzles.methods.create' [
Jan 08 06:44:18 egnor-2020 mise[69591]:   {
Jan 08 06:44:18 egnor-2020 mise[69591]:     "validation": "url",
Jan 08 06:44:18 egnor-2020 mise[69591]:     "code": "invalid_string",
Jan 08 06:44:18 egnor-2020 mise[69591]:     "message": "Invalid url",
Jan 08 06:44:18 egnor-2020 mise[69591]:     "path": [
Jan 08 06:44:18 egnor-2020 mise[69591]:       "url"
Jan 08 06:44:18 egnor-2020 mise[69591]:     ]
Jan 08 06:44:18 egnor-2020 mise[69591]:   }
Jan 08 06:44:18 egnor-2020 mise[69591]: ]
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Object.get error [as error] (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/z>
Jan 08 06:44:18 egnor-2020 mise[69591]:     at ZodObject.parseAsync (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/zod/lib/>
Jan 08 06:44:18 egnor-2020 mise[69591]:     at runMicrotasks (<anonymous>)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Jan 08 06:44:18 egnor-2020 mise[69591]:  => awaited here:
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor>
Jan 08 06:44:18 egnor-2020 mise[69591]:     at packages/meteor.js:367:22
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at imports/lib/models/Model.ts:395:53
Jan 08 06:44:18 egnor-2020 mise[69591]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/me>
Jan 08 06:44:18 egnor-2020 mise[69591]:  => awaited here:
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor>
Jan 08 06:44:18 egnor-2020 mise[69591]:     at imports/server/methods/createPuzzle.ts:77:5
Jan 08 06:44:18 egnor-2020 mise[69591]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/me>
Jan 08 06:44:18 egnor-2020 mise[69591]:  => awaited here:
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor>
Jan 08 06:44:18 egnor-2020 mise[69591]:     at imports/server/methods/defineMethod.ts:54:9
Jan 08 06:44:18 egnor-2020 mise[69591]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/me>
Jan 08 06:44:18 egnor-2020 mise[69591]:  => awaited here:
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor>
Jan 08 06:44:18 egnor-2020 mise[69591]:     at packages/meteor.js:367:22
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at packages/meteor.js:365:18
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at packages/ddp-server/livedata_server.js:827:46
Jan 08 06:44:18 egnor-2020 mise[69591]:     at new Promise (<anonymous>)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at Session.method (packages/ddp-server/livedata_server.js:775:23)
Jan 08 06:44:18 egnor-2020 mise[69591]:     at packages/ddp-server/livedata_server.js:639:43
```

**Comment by egnor** [comment]
Turns out this was because the URL he put in didn't have a leading `https://`. Should have been caught at the user input end, of course!
