### ISSUE TITLE
gdriveActivityFetcher: Sporadic UnhandledPromiseRejectionWarning errors/stacks in logs

### ISSUE THREAD

**Issue by egnor** [deathandmayhem/jolly-roger#1953]
This shows up in our logs sometimes. It's not associated with any obvious user-level failures, so as far as I know it's benign, but seems to reflect some kind of issue? Something about fetching gdrive activity?

(Relatedly, the "doc activity" sparkline for all our test puzzles does seem to be flatlined, despite messing around in the sheet. But I'm not calibrated for how that's supposed to work.)

```
Jan 08 19:55:09 egnor-2020 mise[127813]: (node:127813) UnhandledPromiseRejectionWarning: Error: Internal error encountered.
Jan 08 19:55:09 egnor-2020 mise[127813]:     at Gaxios._request (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/googleapis-common/node_modules/gaxios/build/src/gaxios.js:141:23)
Jan 08 19:55:09 egnor-2020 mise[127813]:     at runMicrotasks (<anonymous>)
Jan 08 19:55:09 egnor-2020 mise[127813]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Jan 08 19:55:09 egnor-2020 mise[127813]:  => awaited here:
Jan 08 19:55:09 egnor-2020 mise[127813]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 08 19:55:09 egnor-2020 mise[127813]:     at imports/server/gdriveActivityFetcher.ts:81:15
Jan 08 19:55:09 egnor-2020 mise[127813]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 08 19:55:09 egnor-2020 mise[127813]:  => awaited here:
Jan 08 19:55:09 egnor-2020 mise[127813]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 08 19:55:09 egnor-2020 mise[127813]:     at imports/server/gdriveActivityFetcher.ts:194:11
Jan 08 19:55:09 egnor-2020 mise[127813]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 08 19:55:09 egnor-2020 mise[127813]:  => awaited here:
Jan 08 19:55:09 egnor-2020 mise[127813]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 08 19:55:09 egnor-2020 mise[127813]:     at imports/server/withLock.ts:68:9
Jan 08 19:55:09 egnor-2020 mise[127813]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 08 19:55:09 egnor-2020 mise[127813]:  => awaited here:
Jan 08 19:55:09 egnor-2020 mise[127813]:     at Function.Promise.await (/home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 08 19:55:09 egnor-2020 mise[127813]:     at imports/server/gdriveActivityFetcher.ts:172:5
Jan 08 19:55:09 egnor-2020 mise[127813]:     at /home/egnor/jolly-roger-deploy/bundle.active/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 08 19:55:09 egnor-2020 mise[127813]: (Use `node --trace-warnings ...` to show where the warning was created)
Jan 08 19:55:09 egnor-2020 mise[127813]: (node:127813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
Jan 08 19:55:09 egnor-2020 mise[127813]: (node:127813) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ebroder** [comment]
Huh. I see these errors periodically too. I had assumed that the activity fetcher would auto-restart on errors but I seem to have been wrong as I also seem to have lost activity fetching. Short-term fix: restart the Jolly Roger process. I'll work on adding some resiliency here.

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **/built_app/bundle/programs/server/npm/node_modules/googleapis-common/node_modules/gaxios/build/src/gaxios.js:141**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/655e86acf52efa0007643ef7?event_id=659bd80500cfffc1b4110000&i=gh&m=li)

**Comment by ebroder** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **/built_app/bundle/programs/server/npm/node_modules/googleapis-common/node_modules/gaxios/build/src/gaxios.js:141**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/655e86acf52efa0007643ef7?event_id=659bd80500cfffc1b4110000&i=gh&m=fx)

**Comment by ebroder** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **Error fetching drive activity**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/655e86acf52efa0007643ef7?event_id=659d0a9200cfe6d3d7ca0000&i=gh&m=ra)

**Comment by ebroder** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **Error fetching drive activity**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/655e86acf52efa0007643ef7?event_id=659fb7d300cfeaddf46c0000&i=gh&m=fx)

**Comment by ebroder** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **Puzzles.methods.create**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/655e86acf52efa0007643ef7?event_id=65a2f17b00d005c4fa6d0000&i=gh&m=ra)
