### ISSUE TITLE
Infinite loop of MediaSoup errors 

### ISSUE THREAD

**Issue by jpd236** [deathandmayhem/jolly-roger#2169]
My JR instance has been up for ~3 weeks.

Starting on 6/4 (two days after https://github.com/deathandmayhem/jolly-roger/issues/2167 happened, with nothing else in between in the server logs), the logs started showing a repeated sequence like this:

```
2024-06-04T02:40:07.127Z mediasoup:ERROR:Channel [pid:54 ChannelMessageRegistrator::RegisterHandler() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists
2024-06-04T02:40:07.170Z mediasoup:ERROR:Channel [pid:54 Worker::HandleRequest() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
2024-06-04T02:40:07.178Z mediasoup:WARN:Channel request failed [method:transport.produceData, id:53]: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
2024-06-04T02:40:51.254Z mediasoup:ERROR:Channel [pid:54 ChannelMessageRegistrator::RegisterHandler() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists
2024-06-04T02:40:51.254Z mediasoup:ERROR:Channel [pid:54 Worker::HandleRequest() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
2024-06-04T02:40:51.255Z mediasoup:WARN:Channel request failed [method:transport.produceData, id:71]: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
2024-06-04T02:41:20.346Z mediasoup:ERROR:Channel [pid:54 ChannelMessageRegistrator::RegisterHandler() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists
2024-06-04T02:41:20.348Z mediasoup:ERROR:Channel [pid:54 Worker::HandleRequest() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
2024-06-04T02:41:20.349Z mediasoup:WARN:Channel request failed [method:transport.produceData, id:88]: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
2024-06-04T02:41:48.808Z mediasoup:ERROR:Channel [pid:54 ChannelMessageRegistrator::RegisterHandler() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists
2024-06-04T02:41:48.809Z mediasoup:ERROR:Channel [pid:54 Worker::HandleRequest() | throwing MediaSoupError: Channel request handler with ID c93bdf42-c7e6-4f63-b288-f8d9546165d2 already exists [method:transport.produceData]
```

The IDs in the messages come and go, but each one appears tens of thousands of times.

Possibly unrelated, but this morning I got a flurry of MongoDB connection errors (MongoPoolClearedError, PoolClearedOnNetworkError, MongoServerSelectionError), and when I tried loading the site a little later it failed the first try and then was quite slow to come up, though it since recovered AFAICT aside from the log spam.

I pushed a new docker image to trigger an update from HEAD (with whatever has landed in Git in the last couple of weeks) + restart and that seems to have stopped the log spam for the moment.

**Comment by jpd236** [comment]
Just happened again (found out because my Papertrail account started approaching quota all of a sudden due to the log spam). Settled down again with just a regular restart.

**Comment by jpd236** [comment]
Someone just reported that they were having trouble staying connected to audio calls, and I checked the server logs and it had entered this state of spitting out "already exists" errors. They said:

> We were all getting hold messages, and then it claimed there were 2-3 versions of each of us in the call while still not having any audio

**Comment by jpd236** [comment]
Unfortunately, the downgrade didn't fix the problem, though it _did_ change the error message showing up in the loop:

```
Jan 12 10:26:48 ip-10-32-0-190/jolly-roger jolly-roger 2025-01-12T18:26:48.209Z mediasoup:ERROR:Channel [pid:54 RTC::Router::OnTransportNewDataProducer() | throwing MediaSoupError: DataProducer already present in mapDataProducers [dataProducerId:8be910b4-fb11-4de8-bd9a-61138319410b] 
Jan 12 10:26:48 ip-10-32-0-190/jolly-roger jolly-roger 2025-01-12T18:26:48.210Z mediasoup:ERROR:Channel [pid:54 Worker::HandleRequest() | throwing MediaSoupError: DataProducer already present in mapDataProducers [dataProducerId:8be910b4-fb11-4de8-bd9a-61138319410b] [method:transport.produceData] 
Jan 12 10:26:48 ip-10-32-0-190/jolly-roger jolly-roger 2025-01-12T18:26:48.210Z mediasoup:WARN:Channel request failed [method:transport.produceData, id:105275]: DataProducer already present in mapDataProducers [dataProducerId:8be910b4-fb11-4de8-bd9a-61138319410b] [method:transport.produceData]
```

**Comment by jpd236** [comment]
Here are the logs from right before the first occurrence:

```
Have not received heartbeat from server, marking as offline: since="Fri Jan 10 2025 18:18:12 GMT+0000 (GMT)" server=W5QbjsaN8JtPBr26m
Have not received heartbeat from server, marking as offline: since="Fri Jan 10 2025 18:18:12 GMT+0000 (GMT)" server=W5QbjsaN8JtPBr26m
New server detected, creating monitor transport: server=fwSuKZjiKamdaFqYa hostname=ip-10-32-0-190 pid=28
Server record unexpectedly deleted: serverId=fwSuKZjiKamdaFqYa pid=28 hostname=ip-10-32-0-190: Error: Server record unexpectedly deleted
    at imports/server/garbage-collection.ts:38:14
    at /built_app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Error connecting monitor transport: direction=receiving transport=5a7977a3-3b7b-4970-b6f1-77ded4bbb5ed initiatingServer=W5QbjsaN8JtPBr26m receivingServer=fwSuKZjiKamdaFqYa: Error: Channel request handler with ID eedbeaaf-4751-492c-8899-c2a403a8b137 already exists [method:transport.produceData]
    at Channel.processMessage (/built_app/bundle/programs/server/npm/node_modules/mediasoup/node/lib/Channel.js:194:37)
    at Socket.<anonymous> (/built_app/bundle/programs/server/npm/node_modules/mediasoup/node/lib/Channel.js:69:34)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
 => awaited here:
    at Function.Promise.await (/built_app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at imports/server/mediasoup.ts:952:25
    at /built_app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by zarvox** [comment]
So first, some background: we have two approaches we use to have servers monitor each other for liveness:

## Servers collection
Each server is [periodically](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/garbage-collection.ts#L75-L78) issuing a write to the Servers collection, where it maintains a record for its `serverId` (randomly generated at process startup).  Each server periodically queries the collection for records which were last updated more than a certain time interval ([currently 120 seconds](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/garbage-collection.ts#L47)) ago.

## WebRTC pipe transport heartbeats
In the mediasoup subsystem, each server creates a router which allows 

## Upon non-liveness observed

Whenever either of these subsystems results in a backend server believing that another backend server has been unresponsive for a time exceeding the tolerance threshold, that server attempts to run server garbage-collection:

* we [remove records from the Subscribers collection](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/subscribers.ts#L15-L17) created by that server.  These records generally power the "who is actively viewing a puzzle?" logic -- we create a subscription when the puzzle page is open.  If the server dies and the client does not subscribe to a different server, we'd like to avoid indicating that they are still actively looking at the page.  We can basically ignore this for now.
* in [medisaoup-api.ts](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/mediasoup-api.ts#L28-L55), we remove any `Peers` and try to take over any `Rooms` that server had previously.
* in [mediasoup.ts](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/mediasoup.ts#L1480-L1502), we remove all of the mediasoup records from the DB that were associated with that server.

Now all of this makes sense to do when a backend is indeed dead.  But based on that `Server record unexpectedly deleted` line, it looks like the process with serverId `fwSuKZjiKamdaFqYa` was still running but observed that some other server had attempted to garbage-collect it, which is not a happy state for a deployment to be in.  I recall having some discussion about STONITH/fencing mechanisms at the time (see https://github.com/deathandmayhem/jolly-roger/pull/1340#discussion_r1073124060) and while we decided not to at the time, that might be worth revisiting.

My read of the sequence of events that triggered this is:

* There seem to be three backend nodes involved: `fwSuKZjiKamdaFqYa`, `mKn9Mpo28q8d6ep2w`, and `W5QbjsaN8JtPBr26m`.  They were likely all healthily connected before these loglines started.
* for some unspecified reason (hypervisor stole CPU time?  network outage?  VM migration caused a pause?  something swapped out?), packets from the server `W5QbjsaN8JtPBr26m` were either dropped or delayed for >5 seconds, and both `fwSuKZjiKamdaFqYa` and `mKn9Mpo28q8d6ep2w` believe it died, and one of those two tried to run GC for it.
* Around the same time, either `mKn9Mpo28q8d6ep2w` or `W5QbjsaN8JtPBr26m` may have marked `fwSuKZjiKamdaFqYa` as down and deleted its record.  I don't actually have loglines saying that happened, but it might have.
* server `fwSuKZjiKamdaFqYa` [upserts its record into the DB](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/garbage-collection.ts#L24-L40), and discovers that this resulted in an insert.
* the insert was observed by `W5QbjsaN8JtPBr26m` as a result of [this query](https://github.com/deathandmayhem/jolly-roger/blob/d1e1b88ea771c5d58d6be78f1160bd08ae454609/imports/server/mediasoup.ts#L339-L341), which tried to initiate a connection to it.
* However, `fwSuKZjiKamdaFqYa` is confused: it received a request to connect from a backend that had already connected to its monitor router previously, and because `fwSuKZjiKamdaFqYa` was unaware that it got incorrectly GC'd, it still has a transport for the relevant UUIDs, and sees this as a duplicate.

I think all of the other log mess is the result of servers marking each other as unresponsive, deleting their DB records, and then the server "coming back" with the same channel IDs.

Unclear if this is the only thing going wrong, but it is definitely A Thing that is definitely unwell in these logs.

FWIW, D&M (and I) generally only run one backend during the off-season, and it would take multiple backend instances to reproduce this particular failure mode, so that's probably one reason why we haven't encountered this ourselves in general development or on our individual servers.  I'll see if I can produce a reasonable test harness to try to reproduce some of these failure modes, or set up a second backend on my server or something.

I think my takeaway is that we probably want to add some additional trace-level logging around what each server believes about its peers (especially when that changes or they take a destructive cleanup action).  We might also want to reconsider STONITH or double-checking how we might achieve idempotency, as well as if any actions that are now async need to be dispatched in a queue to avoid e.g. potentially concurrent `serverRemoved()` and `serverCreated()` calls.

**Comment by jpd236** [comment]
I am _pretty_ sure that I was seeing these issues even when running in "single instance" mode (one EC2 machine). Is it possible that a single instance actually creates multiple virtual "servers" under the covers, or perhaps gets confused and starts fighting itself?

For example, here are some recent logs from my current EC2 instance, which is the only one running:

```
info: [s:ESSMqkB5uXusjeEnj] Cleaning up dead servers: deadServers=k7dk2Z9WturPCDMwy
info: [s:jpbkWbREARe9N3aRR] New server starting: serverId=jpbkWbREARe9N3aRR
info: [s:jpbkWbREARe9N3aRR] Cleaning up dead servers: deadServers=k7dk2Z9WturPCDMwy
verbose: [s:jpbkWbREARe9N3aRR] Discovered announceable IPs: ips=18.209.85.195
info: [s:paohBwNntYQ3cQ76g] Cleaning up dead servers: deadServers=RY5xRrtA2bYNmq2Ba
info: [s:jpbkWbREARe9N3aRR] Cleaning up dead servers: deadServers=zMykpKcT8yThQ6KBq
info: [s:ESSMqkB5uXusjeEnj] New server detected, creating monitor transport: server=jpbkWbREARe9N3aRR hostname=ip-10-32-1-139 pid=24
info: [s:ESSMqkB5uXusjeEnj] New server detected, creating monitor transport: server=paohBwNntYQ3cQ76g hostname=ip-10-32-1-139 pid=25
info: [s:paohBwNntYQ3cQ76g] New server detected, creating monitor transport: server=ESSMqkB5uXusjeEnj hostname=ip-10-32-1-139 pid=7
info: [s:paohBwNntYQ3cQ76g] New server detected, creating monitor transport: server=jpbkWbREARe9N3aRR hostname=ip-10-32-1-139 pid=24
info: [s:jpbkWbREARe9N3aRR] New server detected, creating monitor transport: server=ESSMqkB5uXusjeEnj hostname=ip-10-32-1-139 pid=7
info: [s:jpbkWbREARe9N3aRR] New server detected, creating monitor transport: server=paohBwNntYQ3cQ76g hostname=ip-10-32-1-139 pid=25
```

I could understand that after a watchtower update or something, a server would restart and then clean up the dead records upon coming up. But why would there be multiple dead servers in such a scenario? And why is it then detecting multiple servers, all under the same hostname?

In either case, I tend to agree with the conclusion that this is looking likely to be tied to rogue GCing of tasks that aren't dead.

**Comment by zarvox** [comment]
I'll also throw in a link to #1180 here since it's an open item around "what should our clustering strategy be"
